<?php

namespace FecBundle\Repository;

/**
 * CostsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CostsRepository extends \Doctrine\ORM\EntityRepository
{
}
