<?php

namespace FecBundle\Repository;

/**
 * ReportUploadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportUploadRepository extends \Doctrine\ORM\EntityRepository
{
}
